import type { AnyRecord, BasicReportSnapshot, ExecutableTestDefinition, ScheduleKind } from "./cc-compliance-shared.js";
import {
  BASIC_SET_WAIT_MS,
  BASIC_VALUE_OFF,
  BASIC_VALUE_ON,
  BASIC_VALUE_UNKNOWN,
  DOOR_LOCK_MODE_SECURED,
  DOOR_LOCK_MODE_UNKNOWN,
  DOOR_LOCK_MODE_UNSECURED,
  SCHEDULE_AUTH_WAIT_MS,
  WAIT_SHORT_MS,
  assertBasicDoorLockMapping,
  assertDailyRepeatingSchedule,
  assertDateRecord,
  assertDoorLockReached,
  assertIntegerRange,
  assertOptionalIntegerRange,
  assertOptionalValidBasicValue,
  assertScheduleErased,
  assertScheduleFieldsMatch,
  assertScheduleSlotCount,
  assertScheduleTimeFields,
  assertSupervisionAccepted,
  assertTimeRecord,
  assertTimezoneMatches,
  assertTimezoneOffset,
  assertValidBasicValue,
  assertValidReportDuration,
  assertWeekDaySchedule,
  assertYearDaySchedule,
  compareDeviceTime,
  compareDeviceTimeForOffset,
  eraseScheduleByKind,
  getErrorMessage,
  getScheduleByKind,
  getScheduleSlotCount,
  hasDoorLockState,
  invokeOptional,
  isBasicOnValue,
  isDoorLockUnlocked,
  isEquivalentBasicTargetValue,
  isErasedSchedule,
  isExpectedDoorLockModeUpdate,
  isIntegerInRange,
  isKnownBoltStatus,
  isRecord,
  isRestorableDoorLockMode,
  isValidBasicValue,
  makeDailyRepeatingSchedule,
  makeFutureYearDaySchedule,
  makeInactiveWeekDaySchedule,
  makeScheduleEntryLockTimezone,
  makeTimeCcTimezone,
  makeWeekDaySchedule,
  makeYearDaySchedule,
  nodeCcVersion,
  nodeValues,
  normalizeBasicReport,
  normalizeDoorLockReport,
  numberOrZero,
  optionalNumber,
  parseTimezoneOffsets,
  pickNumber,
  readBasicReport,
  readCcPrecheck,
  readDoorLockReport,
  readDoorLockReportWithCache,
  requireNumber,
  requireScheduleSlots,
  restoreDoorLockMode,
  scheduleSlotInput,
  setDailyRepeatingSchedule,
  setScheduleEntryLockEnabled,
  setWeekDaySchedule,
  setYearDaySchedule,
  snapshotValues,
  supportedCcVersion,
  supportsBasicDoorLock,
  supportsBasicDoorLockV2,
  supportsCommandClass,
  supportsScheduleEntryLockDoorLock,
  timezoneMatches,
  tryReadBasicReport,
  valueSnapshot,
  valuesForCommandClass,
  waitForDoorLockModeUpdate,
  waitForDoorLockStillLocked,
  waitForDoorLockUnlocked,
  writeScheduleByKind,
} from "./cc-compliance-shared.js";

export const timeDefinition: ExecutableTestDefinition = {
  traceCommandClasses: ["Time"],
  meta: {
    id: "time-cc-read-v1",
    key: "time-cc-read",
    name: "Time 时间能力",
    deviceType: "generic-node",
    version: 1,
    enabled: true,
    description: "读取 Time CC 的 time/date/timezone，并与控制器当前时间做基础比较。",
    inputSchema: {},
  },
  supports: supportsCommandClass("Time"),
  async run(context) {
    const precheck = await readCcPrecheck(context, "Time");
    const time = await invokeOptional(context, "Time", "getTime") as AnyRecord | undefined;
    const date = await invokeOptional(context, "Time", "getDate") as AnyRecord | undefined;
    const timezone = await invokeOptional(context, "Time", "getTimezone") as AnyRecord | undefined;
    return { ...precheck, controllerTime: new Date().toISOString(), time, date, timezone };
  },
};
