import type { ExecutableTestDefinition } from "./types.js";
import { binarySwitchDefinition } from "./definitions/binary-switch.js";
import {
  associationDefinition,
  associationGroupInfoDefinition,
  basicDoorLockMappingDefinition,
  basicDoorLockVersionDefinition,
  basicGetReportDefinition,
  basicReportValueDefinition,
  basicSetSecuredMappingDefinition,
  basicSetUnsecuredMappingDefinition,
  basicV2TargetDurationDefinition,
  batteryHealthDefinition,
  deviceResetLocallyDefinition,
  firmwareMetadataDefinition,
  indicatorDefinition,
  manufacturerSpecificDefinition,
  multiChannelAssociationDefinition,
  powerlevelDefinition,
  scheduleEntryLockCapabilitiesDefinition,
  scheduleEntryLockDailyRepeatingReadDefinition,
  scheduleEntryLockDefinition,
  scheduleEntryLockTimeDependencyDefinition,
  scheduleEntryLockTimeOffsetDefinition,
  scheduleEntryLockWeekDayReadDefinition,
  scheduleEntryLockYearDayReadDefinition,
  securitySchemeDefinition,
  supervisionDefinition,
  timeDefinition,
  timeParametersDefinition,
  transportServiceDefinition,
  versionInfoDefinition,
  zwavePlusInfoDefinition,
} from "./definitions/cc-compliance.js";
import { configurationReadWriteDefinition } from "./definitions/configuration-read-write.js";
import { doorLockNotificationDefinition } from "./definitions/door-lock-notification.js";
import { lockBasicDefinition } from "./definitions/lock-basic.js";
import { nodeHealthDefinition } from "./definitions/node-health.js";
import { userCodeAddDefinition, userCodeDeleteDefinition, userCodeEditDefinition } from "./definitions/user-code.js";
import {
  userCredentialAdminPinDefinition,
  userCredentialAssociationDefinition,
  userCredentialCapabilitiesDefinition,
  userCredentialChecksumDefinition,
  userCredentialFingerprintLifecycleDefinition,
  userCredentialIterationDefinition,
  userCredentialNegativeDefinition,
  userCredentialPasswordLifecycleDefinition,
  userCredentialPinLifecycleDefinition,
  userCredentialUserTypeDefinition,
} from "./definitions/user-credential.js";

export const executableDefinitions: ExecutableTestDefinition[] = [
  basicDoorLockVersionDefinition,
  basicGetReportDefinition,
  basicReportValueDefinition,
  basicDoorLockMappingDefinition,
  basicSetSecuredMappingDefinition,
  basicSetUnsecuredMappingDefinition,
  basicV2TargetDurationDefinition,
  scheduleEntryLockCapabilitiesDefinition,
  scheduleEntryLockTimeOffsetDefinition,
  scheduleEntryLockTimeDependencyDefinition,
  scheduleEntryLockWeekDayReadDefinition,
  scheduleEntryLockYearDayReadDefinition,
  scheduleEntryLockDailyRepeatingReadDefinition,
  scheduleEntryLockDefinition,
  transportServiceDefinition,
  associationGroupInfoDefinition,
  deviceResetLocallyDefinition,
  zwavePlusInfoDefinition,
  lockBasicDefinition,
  doorLockNotificationDefinition,
  supervisionDefinition,
  userCodeAddDefinition,
  userCodeEditDefinition,
  userCodeDeleteDefinition,
  userCredentialCapabilitiesDefinition,
  userCredentialPinLifecycleDefinition,
  userCredentialPasswordLifecycleDefinition,
  userCredentialFingerprintLifecycleDefinition,
  userCredentialChecksumDefinition,
  userCredentialAdminPinDefinition,
  userCredentialNegativeDefinition,
  userCredentialIterationDefinition,
  userCredentialUserTypeDefinition,
  userCredentialAssociationDefinition,
  manufacturerSpecificDefinition,
  powerlevelDefinition,
  firmwareMetadataDefinition,
  batteryHealthDefinition,
  associationDefinition,
  versionInfoDefinition,
  indicatorDefinition,
  timeDefinition,
  timeParametersDefinition,
  multiChannelAssociationDefinition,
  securitySchemeDefinition,
  configurationReadWriteDefinition,
  binarySwitchDefinition,
  nodeHealthDefinition,
];
